[package]
name = "crux_time"
description = "Time capability for use with crux_core"
version = "0.8.1"
readme = "README.md"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[features]
typegen = ["crux_core/typegen"]

[dependencies]
chrono = { version = "0.4.39", features = ["serde"], optional = true }
crux_core = { version = "0.11.1", path = "../crux_core" }
serde = { workspace = true, features = ["derive"] }
thiserror = "2.0.11"

[dev-dependencies]
serde_json = "1.0.137"
