[package]
name = "crux_time"
description = "Time capability for use with crux_core"
version = "0.8.0"
readme = "README.md"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[features]
typegen = ["crux_core/typegen"]

[dependencies]
chrono = { version = "0.4.38", features = ["serde"], optional = true }
crux_core = { version = "0.11.0", path = "../crux_core" }
serde = { workspace = true, features = ["derive"] }
thiserror = "1.0.65"

[dev-dependencies]
serde_json = "1.0.132"
