[package]
name = "shared"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[features]
typegen = ["crux_core/typegen"]

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
crux_core = { workspace = true }
crux_http = { workspace = true }
crux_kv = { workspace = true }
crux_platform = { workspace = true }
crux_time = { workspace = true }
lazy_static = "1.5.0"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.137"
uniffi = "0.28.3"
wasm-bindgen = "0.2.100"

[target.uniffi-bindgen.dependencies]
uniffi = { version = "0.28.3", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.28.3", features = ["build"] }
