[package]
name = "xtask"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap = { version = "4.5.38", features = ["derive"] }
human-repr = "1.1.0"
xshell = "0.2.7"

[lints]
workspace = true
