[package]
name = "shared"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[package.metadata.component]
package = "counter-next:shared"

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[[bin]]
name = "codegen"
required-features = ["cli"]

[dependencies]
async-sse = "5.1.0"
chrono = { version = "0.4.41", features = ["serde"] }
crux_core.workspace = true
crux_http.workspace = true
facet = { version = "0.27.16", features = ["bytes", "chrono"] }
futures = "0.3.31"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.141"
url = "2.5.4"

[dev-dependencies]
insta = { version = "1.43.1", features = ["yaml"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
uniffi = "0.29.3"
rand = { version = "0.9.2", features = ["os_rng"] }

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = "0.2.100"
js-sys = "0.3.77"

[target.'cfg(all(target_os = "wasi", target_env = "p2"))'.dependencies]
wit-bindgen = "0.43.0"
wit-bindgen-rt = { version = "0.43.0", features = ["bitflags"] }

[features]
cli = ["crux_core/cli"]
facet_typegen = ["crux_core/facet_typegen"]
typegen = ["crux_core/typegen"]
