[workspace]
members = ["shared", "web-leptos"]
resolver = "2"

[workspace.package]
authors = ["Red Badger Consulting Limited"]
edition = "2021"
repository = "https://github.com/redbadger/crux/"
license = "Apache-2.0"
keywords = ["crux", "crux_core", "cross-platform-ui", "ffi", "wasm"]
rust-version = "1.80"

[workspace.dependencies]
anyhow = "1.0.98"
crux_core = { path = "../../crux_core" }
crux_http = { path = "../../crux_http" }
serde = "1.0.219"
