[package]
name = "shared"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[features]
typegen = ["crux_core/typegen"]

[dependencies]
async-sse = "5.1.0"
async-std = "1.13.0"
chrono = { version = "0.4.39", features = ["serde"] }
crux_core.workspace = true
crux_http.workspace = true
futures = "0.3.31"
lazy_static = "1.5.0"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.138"
uniffi = "0.29.0"
url = "2.5.4"
wasm-bindgen = "0.2.100"

[dev-dependencies]
insta = { version = "1.42.1", features = ["yaml"] }

[target.uniffi-bindgen.dependencies]
uniffi = { version = "0.29.0", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.29.0", features = ["build"] }
