[package]
name = "web-dioxus"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
console_error_panic_hook = "0.1.7"
dioxus = { version = "0.6.3", features = ["web"] }
dioxus-logger = "0.6.2"
futures-util = "0.3.31"
shared = { path = "../shared" }
tracing = "0.1.41"
