[package]
name = "web-leptos"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }

# 0.8 needs resolver=2 which is not good for shared/uniffi-bindgen
# so iOS build struggles. This will all change soon anyway
# (see https://github.com/redbadger/crux/pull/347)
leptos = { version = "=0.7.8", features = ["csr"] }

[lints.clippy]
empty_docs = "allow"
