[package]
name = "web-leptos"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
shared = { path = "../shared" }
leptos = { version = "=0.7.8", features = ["csr"] }

[lints.clippy]
empty_docs = "allow"
